version: '3.1'

services:
  db:
    container_name: webscr-postgres
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_DB: webscr
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
        - "5432:5432"
    networks:
      - webscrnet

  api2:
    build: 
      context: .
      dockerfile: Dockerfile2
    depends_on:
      - db
    ports:
      - "8088:8088" 
    networks:
      - webscrnet 

  api1:
    build: 
      context: .
      dockerfile: Dockerfile1
    ports:
      - "8081:8081"
    networks:
      - webscrnet 
  

networks:
  webscrnet:


